// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJVjSYPzdX7Git3dSRsalrVoUm6g4XQ6Y',
    appId: '1:649801080753:web:4d2e5122e1599467cfa790',
    messagingSenderId: '649801080753',
    projectId: 'blocodenotas-firebase',
    authDomain: 'blocodenotas-firebase.firebaseapp.com',
    storageBucket: 'blocodenotas-firebase.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1wPQAxBdgqKH44YFq4w8G0kyPM65KCIk',
    appId: '1:649801080753:android:93bb18256a586df7cfa790',
    messagingSenderId: '649801080753',
    projectId: 'blocodenotas-firebase',
    storageBucket: 'blocodenotas-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_ljQRVAysrYMiGTpHRsbvEAgo6E2OnQ0',
    appId: '1:649801080753:ios:2f3bd1f6e4a38a13cfa790',
    messagingSenderId: '649801080753',
    projectId: 'blocodenotas-firebase',
    storageBucket: 'blocodenotas-firebase.appspot.com',
    iosBundleId: 'com.example.blocodenotas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJVjSYPzdX7Git3dSRsalrVoUm6g4XQ6Y',
    appId: '1:649801080753:web:68301bdfaedeed8fcfa790',
    messagingSenderId: '649801080753',
    projectId: 'blocodenotas-firebase',
    authDomain: 'blocodenotas-firebase.firebaseapp.com',
    storageBucket: 'blocodenotas-firebase.appspot.com',
  );
}
